version: "2.4"
services:
  db2:
    #image: ibmcom/db2
    #image: icr.io/db2_community/db2
    # Mac M1 workaround: We need to "build" the image ourselves, because docker-compose does not respect the platform setting in the image
    build:
      context: .
      dockerfile: Dockerfile.db2
    platform: linux/amd64
    ports:
      - "50000:50000"
    networks:
      - compose-net
    environment:
      TIMEZONE: Europe/Copenhagen
      LICENSE: accept
      #DB2INSTANCE: db2inst1
      DB2INST1_PASSWORD: password
      #DBNAME: testdb
      #BLU: false
      #ENABLE_ORACLE_COMPATIBILITY: false
      #UPDATEAVAIL: NO
      #TO_CREATE_SAMPLEDB: false
      #REPODB: false
      #IS_OSXFS: false
      #PERSISTENT_HOME: false
      #HADR_ENABLED: false
      #ETCD_ENDPOINT:
      #ETCD_USERNAME:
      #ETCD_PASSWORD:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - compose-net
    environment:
      TIMEZONE: Europe/Copenhagen
    depends_on:
      - db2

# custom network to ensure it is not shared with the default docker bridge
# network
networks:
  compose-net:
    driver: bridge